# Generated by Django 3.2.11 on 2022-01-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="uploads/profile_pics/default.jpg",
                upload_to="uploads/profile_pics/%Y/%m/",
            ),
        ),
    ]
