# Generated by Django 3.2.11 on 2022-01-08 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated at"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VLG", "Vulgarity"),
                            ("VLC", "Violence"),
                            ("ABS", "Abuse"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=3,
                        verbose_name="Report type",
                    ),
                ),
                (
                    "contact_mail",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Contact Email",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="has_user_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Target User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
