# Generated by Django 3.2.11 on 2022-01-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreport",
            name="deleted_timestamp",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Deleted at"
            ),
        ),
    ]
