version: "3.9"

services:
  web:
    build:
      context: .
      args:
        - PROJECT_MODE
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    environment:
      - DJANGO_SECRET_KEY
      - DEBUG
      - DJANGO_SETTINGS_MODULE=floppaverse.settings
      - PYTHONUNBUFFERED=1
      - SHELL=/bin/bash
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
    command:
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|var/lib/docker/.+)($|/)'
    ports:
      - "9100:9100"

volumes:
  pgdata:
  prometheus_data:
