version: "3.9"

services:
  web:
    build:
      context: .
      args:
        - PROJECT_MODE
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    environment:
      - DJANGO_SECRET_KEY
      - DEBUG
      - DJANGO_SETTINGS_MODULE=floppaverse.settings
      - PYTHONUNBUFFERED=1
      - SHELL=/bin/bash
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  pgdata:
