# Generated by Django 3.2.21 on 2023-09-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_auto_20220321_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="in_chat_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_messages",
                to="chat.chatroom",
            ),
        ),
    ]
