# Generated by Django 3.2.11 on 2022-01-10 18:45

import ckeditor.fields
from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to=blog.models.get_thumbnail_upload_path
            ),
        ),
    ]
