{
 "title": "Loki Stats",
 "description": "Visualisations of Loki-aggregated logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Non-HTTP webapp container error logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/lib/docker/containers/ae5a341f0c7cff1c9df0ce85d9f3af59d9271e070a5e91811d9d942724c20d3a/ae5a341f0c7cff1c9df0ce85d9f3af59d9271e070a5e91811d9d942724c20d3a-json.log\"} |= `ERROR: ` !~ `HTTP .*(GET|POST|PUT)`"
    }
   ]
  },
  {
   "title": "HTTP 5xx error logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{filename=\"/var/lib/docker/containers/ae5a341f0c7cff1c9df0ce85d9f3af59d9271e070a5e91811d9d942724c20d3a/ae5a341f0c7cff1c9df0ce85d9f3af59d9271e070a5e91811d9d942724c20d3a-json.log\"} |~ `ERROR: .*(GET|POST|PUT) .* 5\\d{2} `"
    }
   ]
  },
  {
   "title": "Non-HTTP error logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"container_logs\", filename!=\"/var/lib/docker/containers/ae5a341f0c7cff1c9df0ce85d9f3af59d9271e070a5e91811d9d942724c20d3a/ae5a341f0c7cff1c9df0ce85d9f3af59d9271e070a5e91811d9d942724c20d3a-json.log\"} |~ `error|ERROR`"
    }
   ]
  }
 ]
}