groups:
- name: node-exporter
  rules:
  # Available ext4 fs space (in GB)
  - record: node_host_available_fs_space_ext4
    expr: node_filesystem_avail_bytes{fstype="ext4"} / (1024*1024*1024)
  # The average network traffic received, per second, over the last minute (in bytes)
  - record: node_host_network_recv_bytes_over_last_min
    expr: rate(node_network_receive_bytes_total[1m])

  # Alerts
  - alert: Disk almost full
    expr: node_filesystem_avail_bytes{fstype="ext4"} / (1024*1024*1024) < 10
    # raise alert if it keeps firing for 5 minutes
    for: 5m
    # How long an alert will continue firing after the condition that triggered it
    # has cleared.
    keep_firing_for: 15m
    labels:
      severity: "high"
      alerttype: "devops"
    annotations:
      summary: "{{ $labels.mountpoint }} low on free space"
      description: "Data partition {{ $labels.mountpoint }} almost full (less than 10GiB free space left)"
      suggested_troubleshooting_steps: |
        Check the filesystem for large files (use e.g. 'du' to find large files).
        Usual culprits are log files - consider log rotation/offloading to a separate server
  - alert: CPU usage > 80% (10 min)
    expr: 100 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100 > 80
    for: 10m
    labels:
      severity: "high"
      alerttype: "devops"
    annotations:
      summary: "CPU usage > 80%"
      description: "Server CPU usage exceeds 80% for more than 10 minutes."
      suggested_troubleshooting_steps: |
        Check which processes are causing the most CPU usage (use e.g. 'top').
        High CPU usage can also be caused by a commit introducing some CPU-heavy logic.
        It might be worth it to investigate the commit history ('git log', 'git blame', 'git bisect' etc.)
