groups:
- name: django-exceptions
  rules:
  # django 500 response rate by view method (5m)
  - record: floppaverse_http_500_responses_by_view:rate5m
    expr: sum by(view) (rate(django_http_responses_total_by_status_view_method_total{status="500"}[5m]))
  # django views with more than 5% error (500) rates (5m)
  - record: floppaverse_http_views_with_gt_5pc_err_rate:rate5m
    expr: |
      (
        sum by(view) (rate(django_http_responses_total_by_status_view_method_total{status="500"}[5m]))
        /
        sum by(view) (rate(django_http_responses_total_by_status_view_method_total[5m]))
      ) * 100 > 5
  # total django HTTP requests grouped by user agent browser
  - record: floppaverse_http_requests_by_user_agent_browser
    expr: sum by(user_agent_browser) (django_http_requests_total_by_view_transport_method_total)
  # django % of HTTP requests originating from Firefox user agents
  - record: floppaverse_http_requests_percentage_using_firefox
    expr: |
      (
          sum(django_http_requests_total_by_view_transport_method_total{user_agent_browser="firefox"})
        /
          sum(django_http_requests_total_by_view_transport_method_total)
      ) * 100

  # Alerts
  - alert: HTTP 500 error rate greater than 5%
    expr: |
      (
        sum by(view) (rate(django_http_responses_total_by_status_view_method_total{status="500"}[5m]))
        /
        sum by(view) (rate(django_http_responses_total_by_status_view_method_total[5m]))
      ) * 100 > 5
    # raise alert if it keeps firing for 1 minute
    for: 1m
    # How long an alert will continue firing after the condition that triggered it
    # has cleared.
    keep_firing_for: 1m
    labels:
      severity: "high"
    annotations:
      summary: "HTTP 500 rate for view {{ $labels.view }} exceeds 5%: {{ $value }}%"
