name: Test alertmanager configuration

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - "opened"
    branches:
      - "master"

jobs:
  test_alertmanager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install amtool
        run: "sudo apt-get update && sudo apt-get install -y prometheus-alertmanager"
      - name: Validate alertmanager config
        run: "/bin/amtool check-config ./docker/prometheus/alertmanager/alertmanager.yml"
      - name: Test alertmanager config routes
        run: |
          /bin/amtool config routes test --config.file=./docker/prometheus/alertmanager/alertmanager.yml --verify.receivers=floppaverse-webdev-alerts alerttype=webdev
          /bin/amtool config routes test --config.file=./docker/prometheus/alertmanager/alertmanager.yml --verify.receivers=floppaverse-devops-alerts alerttype=devops
