name: Check Codebase using pre-commit

on: [push]

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements/prod.txt'
      - uses: pre-commit/action@v3.0.0
